# Generated by Django 3.0.5 on 2020-07-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedpage', '0006_feed_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='photo',
            field=models.ImageField(blank=True, upload_to='feed_photos'),
        ),
    ]
